version: "3.9"
volumes:
  db_data:
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: shopdb
      DB_USER: postgres
      DB_PASSWORD: password
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
